### PR TITLE
feat(build): support JSON layout

### PR DESCRIPTION
**Pull request by ThomasBurleson**
* support JSON output (in addition to markdown or HTML)
* support sorting by login name
* support loading oAuth access token from `process.env.GITHUB_API_TOKEN`
* simplified startup validation logic
* look absolute path and use for strategy files access

> Supporting JSON and environment variables allows `githubcontrib` to be used in gulp and npm processes

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@mgechev - if you merge. could you update also publish to NPM? Then I could add this package to `angular/material` npm tools for our builds. 

> You have created a great tool!  Thx.

**Comment by mgechev** [comment]
@ThomasBurleson yes sure. There's merge conflict, it'll be great if you can resolve it.

**Comment by ThomasBurleson** [comment]
@mgechev - I do not have write access to your repos and I cannot see what the merge conflicts.

**Comment by mgechev** [comment]
Ready! :-)

**Comment by ThomasBurleson** [comment]
@mgechev  - solved it by:

```console
git remote add upstream https://github.com/mgechev/github-contributors-list.git
git pull --rebase upstream master
git push -f origin master
```

**Comment by ThomasBurleson** [comment]
@mgechev - probably need to publish this 1.2.1 now to npm since it correctly outputs `stringified` JSON.

**Comment by ThomasBurleson** [comment]
@mgechev - hang on! I want to change something real quick.

**Pull request merged**
